import React, { Component } from 'react'
var Scroll = require('react-scroll')
var Link      = Scroll.Link;
// var random = Math.floor(Math.random()*10)
class Car extends Component {
	render(){
		return(
			<div className='car-wrapper'>
				<div className='background-car'></div>
				<div className='star'></div>
				<div className="moon hidden-xs">
					<div className="moon-space"></div>
					<div className="cloud">
						<div className="cloud-sm cl1"></div>
						<div className="cloud-sm cl2"></div>
						<div className="cloud-sm cl3"></div>
						<div className="cloud-sm cl4"></div>
					</div>
					<div className="cloud2">
						<div className="cloud-sm cl1"></div>
						<div className="cloud-sm cl2"></div>
						<div className="cloud-sm cl3"></div>
						<div className="cloud-sm cl4"></div>
					</div>
				</div>
				<div className='sky-scraper-wrapper'>
					<div className="sky-scraper">
						<div className='building-window w1'></div>
						<div className='building-window w1'></div>
						<div className='building-window w1'></div>
						<div className='building-window w1'></div>
						<div className='building-window w1'></div>
						<div className='building-window w1'></div>
						<div className='building-window w1'></div>
						<div className='building-window w1'></div>						
						<div className='building-window w1'></div>
						<div className='building-window w1'></div>						
					</div>
					<div className='baby-sky-scraper'>
						<div className='building-window w2'></div>
						<div className='building-window w2'></div>
						<div className='building-window w2'></div>
						<div className='building-window w2'></div>
						<div className='building-window w2'></div>
						<div className='building-window w2'></div>
						<div className='building-window w2'></div>
						<div className='building-window w2'></div>
						<div className='building-window w2'></div>
						<div className='building-window w2'></div></div>
					<div className='baby-sky-scraper2'>
						<div className='building-window w3'></div>
						<div className='building-window w3'></div>
						<div className='building-window w3'></div>
						<div className='building-window w3'></div></div>
					<div className='baby-sky-scraper3'>
						<div className='building-window w4'></div>
						<div className='building-window w4'></div>
						<div className='building-window w3'></div>
						<div className='building-window w3'></div>
						<div className='building-window w3'></div>
						<div className='building-window w3'></div>
						<div className='building-window w3'></div>
						<div className='building-window w3'></div></div>
					<div className='baby-sky-scraper'>
						<div className='building-window w3'></div>
						<div className='building-window w3'></div>
						<div className='building-window w3'></div>
						<div className='building-window w3'></div></div>
					<div className="sky-scraper">
						<div className='building-window w7'></div>
						<div className='building-window w7'></div>
						<div className='building-window w7'></div>
						<div className='building-window w7'></div></div>
					<div className='baby-sky-scraper3'>
						<div className='building-window w5'></div>
						<div className='building-window w5'></div>
						<div className='building-window w5'></div>
						<div className='building-window w5'></div>
						<div className='building-window w5'></div>
						<div className='building-window w5'></div></div>
					<div className='baby-sky-scraper4'>
						<div className='building-window w10'></div>
						<div className='building-window w10'></div>
						<div className='building-window w10'></div>
						<div className='building-window w10'></div>
						<div className='building-window w10'></div>
						<div className='building-window w10'></div></div>
					<div className='baby-sky-scraper4'>
						<div className='building-window w8'></div>
						<div className='building-window w8'></div>
						<div className='building-window w8'></div>
						<div className='building-window w8'></div>
						<div className='building-window w8'></div>
						<div className='building-window w8'></div>
						<div className='building-window w8'></div>
						<div className='building-window w8'></div></div>
					<div className='baby-sky-scraper'>
						<div className='building-window w8'></div>
						<div className='building-window w7'></div>
						<div className='building-window w7'></div>
						<div className='building-window w7'></div></div>
					<div className='baby-sky-scraper3'>
						<div className='building-window w6'></div>
						<div className='building-window w6'></div>
						<div className='building-window w6'></div>
						<div className='building-window w6'></div>
						<div className='building-window w6'></div>
						<div className='building-window w6'></div></div>
					<div className='baby-sky-scraper'>
						<div className='building-window w4'></div>
						<div className='building-window w4'></div>
						<div className='building-window w4'></div>
						<div className='building-window w4'></div>
						<div className='building-window w4'></div>
						<div className='building-window w4'></div></div>
					<div className='baby-sky-scraper2'>
						<div className='building-window w4'></div>
						<div className='building-window w4'></div>
						<div className='building-window w4'></div>
						<div className='building-window w4'></div>						
						<div className='building-window w4'></div>
						<div className='building-window w4'></div>
						<div className='building-window w4'></div>
						<div className='building-window w4'></div>
					</div>
					<div className="sky-scraper">
						<div className='building-window w2'></div>
						<div className='building-window w2'></div>
						<div className='building-window w2'></div>
						<div className='building-window w2'></div>
						<div className='building-window w2'></div>
						<div className='building-window w2'></div>
						<div className='building-window w2'></div>
						<div className='building-window w2'></div>						
					</div>
					<div className='baby-sky-scraper2'>
						
						<div className='building-window w2'></div>
						<div className='building-window w7'></div>
						<div className='building-window w7'></div>
						<div className='building-window w7'></div>
						<div className='building-window w7'></div>
						
					</div>
					<div className='baby-sky-scraper'>
						<div className='building-window w6'></div>
						<div className='building-window w6'></div>
						<div className='building-window w6'></div>
						<div className='building-window w6'></div>
						<div className='building-window w6'></div>
						<div className='building-window w6'></div></div>
					<div className='baby-sky-scraper2'>
						<div className='building-window w4'></div>
						<div className='building-window w4'></div>
						<div className='building-window w4'></div>
						<div className='building-window w4'></div>
						<div className='building-window w4'></div>
						<div className='building-window w4'></div></div>
					<div className="sky-scraper">
						<div className='building-window w9'></div>
						<div className='building-window w9'></div>
						<div className='building-window w9'></div>
						<div className='building-window w9'></div>
						<div className='building-window w9'></div>
						<div className='building-window w9'></div>						
						<div className='building-window w9'></div>
						<div className='building-window w9'></div>
						<div className='building-window w9'></div>
						<div className='building-window w9'></div></div>
					<div className='baby-sky-scraper4'>
						<div className='building-window w2'></div>
						<div className='building-window w2'></div>
						<div className='building-window w2'></div>
						<div className='building-window w2'></div></div>
					<div className='baby-sky-scraper'>
						<div className='building-window w1'></div>
						<div className='building-window w1'></div>
						<div className='building-window w1'></div>
						<div className='building-window w1'></div></div>
					<div className="sky-scraper">
						<div className='building-window w3'></div>
						<div className='building-window w3'></div>
						<div className='building-window w3'></div>
						<div className='building-window w3'></div></div>
					<div className='baby-sky-scraper3'>
						<div className='building-window w4'></div>
						<div className='building-window w4'></div>
						<div className='building-window w4'></div>
						<div className='building-window w4'></div></div>
					<div className='baby-sky-scraper4'>
						<div className='building-window w8'></div>
						<div className='building-window w8'></div>
						<div className='building-window w8'></div>
						<div className='building-window w8'></div>
						<div className='building-window w8'></div>
						<div className='building-window w8'></div></div>
					<div className='baby-sky-scraper'>
						<div className='building-window w8'></div>
						<div className='building-window w8'></div>
						<div className='building-window w8'></div>
						<div className='building-window w8'></div></div>
					<div className="sky-scraper">
						<div className='building-window w8'></div>
						<div className='building-window w8'></div>
						<div className='building-window w8'></div>
						<div className='building-window w8'></div>
						<div className='building-window w8'></div>
						<div className='building-window w8'></div></div>
					<div className='baby-sky-scraper'>
						<div className='building-window w6'></div>
						<div className='building-window w6'></div>
						<div className='building-window w6'></div>
						<div className='building-window w6'></div>
						<div className='building-window w6'></div>
						<div className='building-window w6'></div></div>
					<div className="sky-scraper">
						<div className='building-window w1'></div>
						<div className='building-window w1'></div>
						<div className='building-window w1'></div>
						<div className='building-window w1'></div>
						<div className='building-window w1'></div>
						<div className='building-window w1'></div>
						<div className='building-window w1'></div>
						<div className='building-window w1'></div>
						<div className='building-window w1'></div>
						<div className='building-window w1'></div></div>
					<div className='baby-sky-scraper2'>
						<div className='building-window w1'></div>
						<div className='building-window w1'></div>
						<div className='building-window w1'></div>
						<div className='building-window w1'></div>
						<div className='building-window w1'></div>
						<div className='building-window w1'></div></div>
					<div className='baby-sky-scraper3'>
						<div className='building-window w2'></div>
						<div className='building-window w2'></div>
						<div className='building-window w2'></div>
						<div className='building-window w2'></div>
						<div className='building-window w2'></div>
						<div className='building-window w2'></div></div>
					<div className='baby-sky-scraper4'>
						<div className='building-window w3'></div>
						<div className='building-window w3'></div>
						<div className='building-window w3'></div>
						<div className='building-window w3'></div>
						<div className='building-window w3'></div>
						<div className='building-window w3'></div></div>
					<div className='baby-sky-scraper2'>
						<div className='building-window w5'></div>
						<div className='building-window w5'></div>
						<div className='building-window w5'></div>
						<div className='building-window w5'></div>
						<div className='building-window w5'></div>
						<div className='building-window w5'></div></div>
					<div className='baby-sky-scraper4'>
						<div className='building-window w6'></div>
						<div className='building-window w6'></div>
						<div className='building-window w6'></div>
						<div className='building-window w6'></div>
						<div className='building-window w6'></div>
						<div className='building-window w6'></div></div>
					<div className="sky-scraper">
						<div className='building-window w7'></div>
						<div className='building-window w7'></div>
						<div className='building-window w7'></div>
						<div className='building-window w7'></div>
						<div className='building-window w7'></div>
						<div className='building-window w7'></div>
						<div className='building-window w7'></div>
						<div className='building-window w7'></div>
						<div className='building-window w7'></div>
						<div className='building-window w7'></div></div>
					<div className='baby-sky-scraper'>
						<div className='building-window w8'></div>
						<div className='building-window w8'></div>
						<div className='building-window w8'></div>
						<div className='building-window w8'></div>
						<div className='building-window w8'></div>
						<div className='building-window w8'></div>
						<div className='building-window w8'></div>
						<div className='building-window w8'></div></div>
					<div className='baby-sky-scraper2'>
						<div className='building-window w9'></div>
						<div className='building-window w9'></div>
						<div className='building-window w9'></div>
						<div className='building-window w9'></div>
						<div className='building-window w9'></div>
						<div className='building-window w9'></div></div>
					<div className='baby-sky-scraper3'>
						<div className='building-window w4'></div>
						<div className='building-window w4'></div>
						<div className='building-window w4'></div>
						<div className='building-window w4'></div></div>
					<div className='baby-sky-scraper'>
						<div className='building-window w3'></div>
						<div className='building-window w3'></div>
						<div className='building-window w3'></div>
						<div className='building-window w3'></div>
						<div className='building-window w3'></div>
						<div className='building-window w3'></div></div>
					<div className="sky-scraper">
						<div className='building-window w2'></div>
						<div className='building-window w2'></div>
						<div className='building-window w2'></div>
						<div className='building-window w2'></div>
						<div className='building-window w2'></div>
						<div className='building-window w2'></div>
						<div className='building-window w2'></div>
						<div className='building-window w2'></div>
						<div className='building-window w2'></div>
						<div className='building-window w2'></div></div>
					<div className='baby-sky-scraper3'>
						<div className='building-window w6'></div>
						<div className='building-window w6'></div>
						<div className='building-window w6'></div>
						<div className='building-window w6'></div></div>
					<div className='baby-sky-scraper'>
						<div className='building-window w7'></div>
						<div className='building-window w7'></div>
						<div className='building-window w7'></div>
						<div className='building-window w7'></div>
						<div className='building-window w7'></div>
						<div className='building-window w7'></div></div>
					<div className='baby-sky-scraper2'>
						<div className='building-window w9'></div>
						<div className='building-window w9'></div>
						<div className='building-window w9'></div>
						<div className='building-window w9'></div>
						<div className='building-window w9'></div>
						<div className='building-window w9'></div>
						<div className='building-window w9'></div>
						<div className='building-window w9'></div></div>
					<div className='baby-sky-scraper3'>
						<div className='building-window w10'></div>
						<div className='building-window w10'></div>
						<div className='building-window w10'></div>
						<div className='building-window w10'></div>
						<div className='building-window w10'></div>
						<div className='building-window w10'></div></div>
					<div className='baby-sky-scraper4'>
						<div className='building-window w4'></div>
						<div className='building-window w4'></div>
						<div className='building-window w4'></div>
						<div className='building-window w4'></div>
						<div className='building-window w4'></div>
						<div className='building-window w4'></div></div>
					<div className='baby-sky-scraper2'>
						<div className='building-window w6'></div>
						<div className='building-window w6'></div>
						<div className='building-window w6'></div>
						<div className='building-window w6'></div>
						<div className='building-window w6'></div>
						<div className='building-window w6'></div>
						<div className='building-window w6'></div>
						<div className='building-window w6'></div></div>
					<div className='baby-sky-scraper'>
						<div className='building-window w7'></div>
						<div className='building-window w7'></div>
						<div className='building-window w7'></div>
						<div className='building-window w7'></div>
						<div className='building-window w7'></div>
						<div className='building-window w7'></div></div>
					<div className='baby-sky-scraper4'>
						<div className='building-window w5'></div>
						<div className='building-window w5'></div>
						<div className='building-window w5'></div>
						<div className='building-window w5'></div></div>
					<div className="sky-scraper">
						<div className='building-window w4'></div>
						<div className='building-window w4'></div>
						<div className='building-window w4'></div>
						<div className='building-window w4'></div>
						<div className='building-window w4'></div>
						<div className='building-window w4'></div>
						<div className='building-window w4'></div>
						<div className='building-window w4'></div>
						<div className='building-window w4'></div>
						<div className='building-window w4'></div></div>
					<div className='baby-sky-scraper3'>
						<div className='building-window w3'></div>
						<div className='building-window w3'></div>
						<div className='building-window w3'></div>
						<div className='building-window w3'></div></div>
					<div className='baby-sky-scraper4'>
						<div className='building-window w1'></div>
						<div className='building-window w1'></div>
						<div className='building-window w1'></div>
						<div className='building-window w1'></div>
						<div className='building-window w1'></div>
						<div className='building-window w1'></div></div>
					<div className='baby-sky-scraper'>
						<div className='building-window w2'></div>
						<div className='building-window w2'></div>
						<div className='building-window w2'></div>
						<div className='building-window w2'></div></div>
					<div className="sky-scraper">
						<div className='building-window w3'></div>
						<div className='building-window w3'></div>
						<div className='building-window w3'></div>
						<div className='building-window w3'></div>
						<div className='building-window w3'></div>
						<div className='building-window w3'></div></div>					
					<div className='baby-sky-scraper'>
						<div className='building-window w4'></div>
						<div className='building-window w4'></div></div>
					<div className="sky-scraper">
						<div className='building-window w7'></div>
						<div className='building-window w7'></div>
						<div className='building-window w7'></div>
						<div className='building-window w7'></div>
						<div className='building-window w7'></div>
						<div className='building-window w7'></div>
						<div className='building-window w7'></div>
						<div className='building-window w7'></div></div>
					<div className='baby-sky-scraper3'>
						<div className='building-window w8'></div>
						<div className='building-window w8'></div>
						<div className='building-window w8'></div>
						<div className='building-window w8'></div></div>
					<div className='baby-sky-scraper4'>
						<div className='building-window w10'></div>
						<div className='building-window w10'></div>
						<div className='building-window w10'></div>
						<div className='building-window w10'></div>
						<div className='building-window w10'></div>
						<div className='building-window w10'></div></div>
					<div className='baby-sky-scraper'>
						<div className='building-window w9'></div>
						<div className='building-window w9'></div>
						<div className='building-window w9'></div>
						<div className='building-window w9'></div>
						<div className='building-window w9'></div>
						<div className='building-window w9'></div></div>
					<div className="sky-scraper">
						<div className='building-window w6'></div>
						<div className='building-window w6'></div>
						<div className='building-window w6'></div>
						<div className='building-window w6'></div>
						<div className='building-window w6'></div>
						<div className='building-window w6'></div>
						<div className='building-window w6'></div>
						<div className='building-window w6'></div>
						<div className='building-window w6'></div>
						<div className='building-window w6'></div>
						<div className='building-window w5'></div></div>
					<div className='baby-sky-scraper2'>
						<div className='building-window w5'></div>
						<div className='building-window w5'></div>
						<div className='building-window w5'></div>
						<div className='building-window w5'></div>
						<div className='building-window w5'></div>
						<div className='building-window w5'></div>
						<div className='building-window w5'></div>
						<div className='building-window w5'></div></div>
					<div className='baby-sky-scraper4'>
						<div className='building-window w4'></div>
						<div className='building-window w4'></div>
						<div className='building-window w4'></div>
						<div className='building-window w4'></div></div>
					<div className='baby-sky-scraper2'>
						<div className='building-window w3'></div>
						<div className='building-window w3'></div>
						<div className='building-window w3'></div>
						<div className='building-window w3'></div>
						<div className='building-window w3'></div>
						<div className='building-window w3'></div>
						<div className='building-window w3'></div>
						<div className='building-window w3'></div></div>
					<div className='baby-sky-scraper4'>
						<div className='building-window w6'></div>
						<div className='building-window w6'></div>
						<div className='building-window w6'></div>
						<div className='building-window w6'></div>
						<div className='building-window w6'></div>
						<div className='building-window w6'></div></div>
				</div>
				<div className='street-light-wrapper'>
					<div className='street-light-pole'></div>
					<div className='street-top-pole'></div>
					<div className='street-top-light'></div>
					<div className='street-light-bulb'></div>
				</div>
				{/*****************************************************************************/}
				{/*****************************************************************************/}
				{/************************************ Car ************************************/}
				{/*****************************************************************************/}
				{/*****************************************************************************/}
				<div id="car" className="moveUp">
					<div className='gradient'></div>	
					<div className="upperPart">
						<div className="triangle">
							<div className="triangle-body">
								<div className="window"></div>
							</div>	
						</div>
					</div>
					<div className='light'></div>
					<div className="body">
						<div className="door"></div>
						<div className="knob"></div>
						
						<div className="headlight"></div>
						<div className="tail-light"></div>
						
					</div>

					<div className="circle1 rotate">
						<div className="rim">
							<div className='rim-inside r1'></div>
							<div className='rim-inside r2'></div>
							<div className='rim-inside r3'></div>
							<div className='rim-inside-circle'></div>
						</div>
					</div>		

					<div className="circle2 rotate">
						<div className="rim">
							<div className='rim-inside r1'></div>
							<div className='rim-inside r2'></div>
							<div className='rim-inside r3'></div>
							<div className='rim-inside-circle'></div>
						</div>
					</div>
				</div>

				<div className="road">
					<div className="car-shadow"></div>
					<div className='white-line'></div>
				</div>

				{/*<div className='fly letterK'>P</div>
				<div className='fly letterA'>A</div>
				<div className='fly letterN'>U</div>	
				<div className='fly fly-number letterG'>L</div>
				<div className='fly letter1'>H</div>
				<div className='fly letter2'>I</div>
				<div className='fly letter3'>I</div>
				<div className='fly letter4'>A</div>
				<div className='fly fly-number letter5'>M</div>
				<div className='fly letter6'>L</div>
				<div className='fly letter7'>I</div>
				<div className='fly letter8'>N</div>
				<div className='fly letter9'>G</div>*/}

			<div className='intro-wrapper'>	
				<div className='intro-header'>Front End Development</div>
				<div className='intro-description'>HTML,&nbsp; CSS / SASS,&nbsp; JavaScript / jQuery,&nbsp; React.js</div>
			</div>			
			<Link to="portfolio" spy={true} smooth={true} duration={1000} ><div className='arrow bounce'></div></Link>
			</div>

		)
	}
}

export default Car